"""Add category column to book table

Revision ID: 9dfe64d6ae1b
Revises: c7390c0ec0b6
Create Date: 2025-01-22 10:34:24.349021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfe64d6ae1b'
down_revision = 'c7390c0ec0b6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=20), nullable=False, server_default='Physical'))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Unread'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False, server_default='false'))
    # Remove the server default after the migration
    op.execute("ALTER TABLE book ALTER COLUMN format DROP DEFAULT")
    op.execute("ALTER TABLE book ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE book ALTER COLUMN archived DROP DEFAULT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('format')
        batch_op.drop_column('archived')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
